### ISSUE TITLE
IO error ... /LOCK: The system cannot find the path specified.

### ISSUE THREAD

**Issue by lethak** [extremeheat/node-leveldb-zlib#11]
Hello, I am getting an error on win10 since the directory separator is "\\" instead of "/".

```
IO error: C:\Users\XXX\AppData\Roaming\XXX\XXX.ldb/LOCK: IO error: C:\Users\XXX\AppData\Roaming\XXX\XXX.ldb/LOCK: The system cannot find the path specified.
```

It appears to be coming from `leveldb-zlib/leveldb-mcpe/db/filename.cc:55`

```cpp
std::string LockFileName(const std::string& dbname) {
  return dbname + "/LOCK";
}
```

Any idea for a workaround would be much apreciated

**Comment by extremeheat** [comment]
CI is passing fine on Windows. The problem is on your file system, I recommend restarting the machine and trying again.

**Comment by extremeheat** [comment]
Closing as waiting for information
